INHERIT: docs/mkdocs-base.yml

site_name: pycharting
site_description: Add your description here.
site_url: https://alihaskar.github.io/pycharting/
repo_url: https://github.com/alihaskar/pycharting
repo_name: alihaskar/pycharting
edit_uri: edit/main/

docs_dir: docs

nav:
  - Home: index.md
  - Reports:
      - Test Report: reports/html-report/report.html
      - Coverage Report: reports/html-coverage/index.html
